apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: gp2
  hostPath:
    path: /data/volumes/user-pv   # Where all the hard drives are mounted
    type: DirectoryOrCreate
